### PR TITLE
Add new plugin can show funs count for bilibili.com.

### PR DESCRIPTION
**Pull request by leeeboo**
bilibili.com is a video site like youtube.com.
It very popular in China.
I made a plugin for it to show funs count.
Already tested. Works well.

### CODE REVIEW

**Comment by Blueforcer** [comment]
Awesome! Keep going!
Would be nice to share the project in china!

**Comment by leeeboo** [comment]
> Awesome! Keep going!
> Would be nice to share the project in china!

Thanks! I am still working on some other chinese website plugin.

**Comment by Blueforcer** [comment]
Checkout the new template. 


Its lot easier!




Outlook für Android herunterladen







On Sun, Apr 21, 2019 at 2:32 AM +0200, "Albert Lee" <notifications@github.com> wrote:













Awesome! Keep going!

Would be nice to share the project in china!



Thanks! I am still working on some other chinese website plugin.

**Comment by leeeboo** [comment]
Thanks!

**Comment by leeeboo** [comment]
@Blueforcer I found this plugin is in new appstore. But you may did wrong compile. The setting page is wrong(it 's not my app' s settings...).
My app settings is :

[https://github.com/awtrix/AWTRIX2.0-Apps/blob/master/bilibiliPlugin/bilibiliPlugin.bas#L29](https://github.com/awtrix/AWTRIX2.0-Apps/blob/master/bilibiliPlugin/bilibiliPlugin.bas#L29)

image

**Comment by leeeboo** [comment]
@Blueforcer and the version wrong also. my app version is 1.0
So I think maybe your auto script compile and push plugin to app store has some errors.

**Pull request merged**
